### PR TITLE
apply real-world data for genre popularity

### LINKED ISSUE #39: Apply real-ish world data to genre popularity
Wonder if there's a way to derive fan sentiment for genres from real-world data, like... surely the potential fanbase for an Big Band Orchestra is smaller than for a Boy Band.

### PR DESCRIPTION
**Pull request by ryanckulp**
resolves #39 

### description

`Lastfm.sentiment` assigns local genres a popularity score based on tag mappings from top 100 artists on Lastfm.

is built so we can add additional genres to DB anytime, and this service will "just work."

### implementation notes

some artists have dozens of tags, so i'm only summing top 5 tags (`tags[0..5]`). 

see the difference between 3 tags summing vs 5 tags summing [here](https://docs.google.com/spreadsheets/d/1P57BdP0F8aREJ8sQ_tvnphl2gFkvEVF8eVsGCDRms1I/edit?usp=sharing).

service could be extended by considering _exact_ tag "counts" per genre vs relative counts (rock > dance).

this query takes around 10 seconds. storing api key in `application.yml` because it's public/safe, not shared_secret.

### what i did

fans are adjusted in 3 places:

1. app/services/band/daily_update.rb (down)
2. app/services/band/play_gig.rb (up)
3. app/services/recording/calc_earnings.rb (up or down)

**daily_update.rb**

replaced static decay rate (10%) with dynamic 0 to 15% decay rate, in parity with real world genre sentiment. 

top ranking genre (ie Rock) bands would decay only 5%, and lowest ranking bands (ie Folk) would decay fans by 20%. 

simply increase `3.25` figure in `impact = ...` LOC to make decay less dramatic or change `0.95 - impact` to something like `1 - impact` to allow top genre bands to not decay fans at all in this procedure.

**play_gig.rb**

could leverage this same `Lastfm.sentiment` response to make the assignment of `buzz` more dynamic, ie `buzz = band.buzz + stack-rank-multiplier`, however remember the sentiment procedure is "expensive."

**calc_earnings.rb**

i'd do a similar adjustment to `buzz`, as well as decrease the impact of `RECORDING_FAN_DECAY_PER_DAY`, just like in `daily_update`.

### next steps

1. let me know if you think adjusting buzz + recording fan decay makes sense. in theory i'd rather we
remove all constants and tie everything to real world data.
2. make a prod API key for Lastfm: https://www.last.fm/api/account/create
3. new db table to store sentiments ~daily, or run dozens of long jobs /day every time gig is played?
4. need this ranking extended to account for granularity popularity difference (ie Rock 523 vs Dance 386) vs relative difference (Rock `#1`, Dance `#2`, etc)?

### CODE REVIEW

**Comment by Shpigford** [comment]
@ryanckulp Such a great first go! Really not much I'd change. It's one of those things that just needs to be tried out and see how it works in practice.

That being said, I _do_ think we need to store all of this data locally and just retrieve from Last.fm in a background job once a day. If you could tack that on to this PR, then I think it'll be good to go!

**Comment by ryanckulp** [comment]
cool! thanks, coming up

**Comment by ryanckulp** [comment]
okey dokey, what do you think of this?

new table makes no hard assumptions, thus we can add lots of sources and store / analyze those results however we want.

just swapped the `daily_update` for now. if this looks good i can apply other ideas (buzz +/-) to 2 remaining spots.

**Comment by Shpigford** [comment]
@ryanckulp Looks good to me!

**Comment by ryanckulp** [comment]
right on, now we're using this data in all 3 places.

static decay rate was 0.05, now it ranges 0.01 (most popular genre in real world) to 0.06.

as for buzz, same concept. most popular bands get extra buzz, between 0 - 5.

**Comment by Shpigford** [comment]
@ryanckulp Fantastic! Any specific instructions for merging this? Presumably just merge + run migrations and it should be good to go?

**Comment by ryanckulp** [comment]
yep, merge, run seed data (to guarantee at least 1 recent sentiment), and plug in a production API key as ENV var.

https://www.last.fm/api/account/create

**Comment by Shpigford** [comment]
@ryanckulp Pushed to production! Really great job on this, Ryan.

**Comment by ryanckulp** [comment]
thank you Josh! had fun doing it

**Pull request merged**
