### PR TITLE
More services

### PR DESCRIPTION
**Pull request by bsharpe**
- Add RecordAlbum service
- Add Release service
- Add Recording::CalcEarnings service
- Removed ActivityWorker (as it wasn't being used)
- Removed unnecessary Helpers
- Moved some hard-coded numbers into `config/initializers/constants.rb` (Centrally located)
- Added test specs for new services

### CODE REVIEW

**Comment by Shpigford** [comment]
@bsharpe Getting `ActivitiesController#new is missing a template for this request format and variant` error when trying to record an album. Last time this happened on a different action it was due to some of the params not getting passed/set properly.

**Comment by Shpigford** [comment]
@bsharpe Also getting this same error for the Release action.

**Comment by bsharpe** [comment]
@Shpigford fixed.

**Comment by Shpigford** [comment]
@bsharpe Figured it out. Incorrect param name. Working now.

**Pull request merged**
