### PR TITLE
Add RSpec, some tests, cleanups, and dev environment happiness

### PR DESCRIPTION
**Pull request by bsharpe**
- add and setup `rspec`
- create services for big hunks of code in `Member` and `DailyRunningFinancialWorker`
- write tests for those services
- add `annotate_models` and annotated the models
- added `ensurance` so you can `Model.ensure(<something>) or Model.ensure!(<something>)`
- add `seedbank` and create seed files for the various models 
- add `factory_bot` and factories for models required for testing
- added `better_errors, hirb, bundleup, awesome_print, fast_blank, colorize` for better development
- added rubocop as the style policeman
- autofixed as many of the rubocop things as possible

### CODE REVIEW

**Comment by Shpigford** [comment]
Hot dang @bsharpe! Going to pull this locally and make sure it all works well. This is amazing!

**Comment by Shpigford** [comment]
@bsharpe I see a lot of the ID's were changed from integers to bigint's, but looks like that happened directly in the schema file. Is that correct? Or is there some migration file I'm missing?

**Comment by Shpigford** [comment]
@bsharpe Gotcha. I just created a new migration (to update some other column types for another feature) and it changed all those _back_ to `int`'s. Wondering if there's some setting somewhere that I need to change.

**Comment by Shpigford** [comment]
@bsharpe And actually, just merged your Verb change and when I run `rake db:migrate` locally, it does the same thing...changes all of those `bigint` columns back to `int`.

**Comment by bsharpe** [comment]
Hmm...  I'm using PG 10.3 from `brew install postgres` -- maybe that's the issue...

**Comment by Shpigford** [comment]
I'm using 10.3 as well (as is Heroku).

```
> ActiveRecord::Base.connection.select_value('SELECT version()')
   (1.4ms)  SELECT version()
 => "PostgreSQL 10.3 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit" 
```

But it's definitely converting those ID's right back to ints every time I run a migration.

screen shot 2018-04-13 at 8 47 10 am

**Comment by Shpigford** [comment]
Wonder if we need to create an explicit migration to change them just to force it?

**Pull request merged**
